name: perfume_control_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^2.1.0
  get_it: ^9.2.0
  google_fonts: ^8.0.1
  intl: ^0.20.2
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
